name: Require “Allow Edits”

on: [pull_request_target]

permissions:
  contents: read

jobs:
  _:
    permissions:
      pull-requests: read
    name: "Require “Allow Edits”"

    runs-on: ubuntu-latest

    steps:
    - name: Harden Runner
      uses: step-security/harden-runner@v2
      with:
        allowed-endpoints:
          api.github.com:443
    - uses: ljharb/require-allow-edits@main
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
- ชื่อ : แคช
  ใช้: actions/cache@v4.2.3
  กับ:
    # รายการไฟล์ ไดเรกทอรี และรูปแบบไวลด์การ์ดที่ต้องแคชและเรียกคืน
    เส้นทาง: 
    # คีย์ที่ชัดเจนสำหรับการคืนค่าและบันทึกแคช
    สำคัญ: 
    # สตริงหลายบรรทัดที่เรียงลำดับซึ่งแสดงรายการคีย์ที่ตรงกับคำนำหน้า ซึ่งใช้ในการคืนค่าแคชเก่าหากไม่มีการเข้าถึงแคชสำหรับคีย์ โปรดทราบว่า `cache-hit` คืนค่า false ในกรณีนี้
    restore-keys: # ตัวเลือก
    # ขนาดชิ้นส่วนที่ใช้ในการแบ่งไฟล์ขนาดใหญ่ในระหว่างการอัปโหลดเป็นหน่วยไบต์
    ขนาดชิ้นส่วนการอัปโหลด: # ตัวเลือก
    # บูลีนเสริมเมื่อเปิดใช้งาน ช่วยให้ผู้รัน Windows สามารถบันทึกหรือเรียกคืนแคชที่สามารถเรียกคืนหรือบันทึกบนแพลตฟอร์มอื่นได้ตามลำดับ
    enableCrossOsArchive: # ตัวเลือก ค่าเริ่มต้นคือเท็จ
    # ล้มเหลวในเวิร์กโฟลว์หากไม่พบรายการแคช
    fail-on-cache-miss: # ตัวเลือก ค่าเริ่มต้นคือ false
    # ตรวจสอบว่ามีรายการแคชสำหรับอินพุตที่กำหนดหรือไม่ (คีย์, คีย์คืนค่า) โดยไม่ต้องดาวน์โหลดแคช
    ค้นหาเท่านั้น: # ตัวเลือก ค่าเริ่มต้นคือเท็จ
    # รันขั้นตอนการโพสต์เพื่อบันทึกแคชแม้ว่าขั้นตอนอื่นก่อนหน้านี้จะล้มเหลว
    save-always: # ตัวเลือก, ค่าเริ่มต้นคือ false
           
